### ISSUE TITLE
Development branch, 2.3?

### ISSUE THREAD

**Issue by nickdunn** [brockpetrie/dynamictextgroup#11]
Hi mate — is the development branch going to be for 2.3 compatibility? I've got a need for this field on a 2.3 project. Should I use the development branch? Apparently you may not need Stage any longer, using duplicator instead?

/cc @nilshoerrmann

**Comment by nilshoerrmann** [comment]
There was someone on the forum saying he'll be updating this extension.

**Comment by nickdunn** [comment]
@iwyg how did you get on?

**Comment by iwyg** [comment]
Still working on this. I have a few days off from now. Maybe next monday

**Comment by nickdunn** [comment]
Cool thanks. I have a fairly urgent need for this, so would be happy to finish off what you have started. But equally I am happy to wait until Monday :-)

**Comment by iwyg** [comment]
@nickdunn just committed my changes to the development branch, so feel free to test it.

**Comment by brockpetrie** [comment]
Latest version on the dev branch is built for 2.3+!
