### ISSUE TITLE
Referene to a missing js file in the code

### ISSUE THREAD

**Issue by andrewminton** [brockpetrie/dynamictextgroup#15]
There is a reference to a missing https://github.com/brockpetrie/dynamictextgroup/blob/development/fields/field.dynamictextgroup.php#L188

When you create a field all is good, When you edit a section with dynamictextgroup field the error in layout occurs. When I inspect element I noticed that a reference to the missing script came up.

**Comment by designermonkey** [comment]
Andrew, does this make the field unusable? I need this in a project.

**Comment by andrewminton** [comment]
Yes mate, The presentation is all to pot in the Section entry editor.

I've searched Brocks code on all branches and there is no reference to this file in the repo.

**Comment by designermonkey** [comment]
Damn. Rethinking time then. Cheers Andrew.

andrewminton wrote:

**Comment by andrewminton** [comment]
It may be a refactoring of what JS file is loaded at first build of section with dynamictextgroup and see what is in use there..

I got a feeling there is no need for that bit of code, cos it worked when I first created the section and started adding Dynamic Text Entry Fields.

**Comment by designermonkey** [comment]
Ok, when I get to that section, I'll take a look at it.

andrewminton wrote:

**Comment by andrewminton** [comment]
Tidy..

I'm in there too as well.. local build with 2.3.2 to test it out.. I am using the Development Branch and that's where I'm experiencing this issue.. I think Master branch is fine as it has no reference to the custom select2.custom.js file in there.

**Comment by designermonkey** [comment]
`master` isn't compatible with `2.3.x` sadly.

I've run into other issues with the JS in this as it's only able to run a single instance of the field, and I haven't got time to rejig it to work for multiple, so have dropped it from the spec.

**Comment by andrewminton** [comment]
Yeh, I think Multiple instances was on the TODO list for v3.

**Comment by andrewminton** [comment]
A good duplicator to trump SSM is in dire need of some investment me
thinks.. so much promise.. Rowans Content
Fieldhttps://github.com/rowan-lewis/content_fieldis quite useful at
the moment.

**Comment by brockpetrie** [comment]
I've removed the line that references the missing file, so this should be fixed now. Thanks Andrew

**Comment by andrewminton** [comment]
Ahh right, so it just wasn't needed then. Might file a small issue with styling looking all wonky when editing a section entry using develpoment branch.. will test first though.. cheers.
