### ISSUE TITLE
Drag handle in field settings

### ISSUE THREAD

**Issue by nilshoerrmann** [brockpetrie/dynamictextgroup#3]
I see this black square in the section settings:

![Settings](http://projekte.nilshoerrmann.de/screenshots/sym_dynamictextgroup.png)

Using Safari 5.1 und Mac OS Lion.

**Comment by nilshoerrmann** [comment]
It's just fine using Firefox 6 and Google Chrome.

**Comment by brockpetrie** [comment]
Thanks, Nils!

Fixed by adding the following rule to `assets/dynamictextgroup.fieldeditor.css`:

```
.ui-resizable-e { opacity:0; }
```

Could you add that rule and confirm? Feel free to close this if it works.

**Comment by brockpetrie** [comment]
This should be resolved as of `2.0dev6`. Thanks again, Nils!

**Comment by nilshoerrmann** [comment]
Sorry for not replying earlier: yes, it's fixed.
